spring:
  application:
    name: customer-service
  rabbitmq:
    host: 192.168.251.157
    port: 5673
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: bindings