spring:
  application:
    name: customer-service
  rabbitmq:
    host: 192.168.251.157
    port: 5673
    username: admin
    password: admin
  cloud:
    stream:
      bindings:
        inboundOrders:
          group: ordersGroup
      rabbit:
        bindings:
          inboundOrders:
            consumer:
              auto-bind-dlq: true



#spring.cloud.stream.bindings.input1.destination: customer
#spring.cloud.stream.bindings.input2.destination: customer1

#spring.cloud.stream.bindings.input.group: ordersGroup

server.port: 0