spring:
  application:
    name: bank-b
  datasource:
    url: jdbc:mysql://192.168.251.157:3306/es-bank-b?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
axon:
  serializer:
    general: jackson